import { StyleSheet } from 'react-native';

export const lightColors = {
  primary: '#4F46E5',
  primaryLight: '#EEF2FF',
  primaryDark: '#3730A3',
  secondary: '#10B981',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  text: '#0F172A',
  textLight: '#64748B',
  danger: '#F43F5E',
  warning: '#F59E0B',
  border: '#E2E8F0',
  cardShadow: 'rgba(15, 23, 42, 0.04)',
  overlay: 'rgba(0,0,0,0.5)',
  skeleton: '#E5E7EB',
  skeletonHighlight: '#F3F4F6',
  tabBar: '#FFFFFF',
  inputBg: '#F3F4F6',
  headerBg: '#FFFFFF',
  statBg: '#FFFFFF',
  dangerLight: '#FEF2F2',
  warningLight: '#FFFBEB',
};

export const darkColors = {
  primary: '#818CF8',
  primaryLight: '#1E1B4B',
  primaryDark: '#A5B4FC',
  secondary: '#34D399',
  background: '#0F172A',
  surface: '#1E293B',
  text: '#F1F5F9',
  textLight: '#94A3B8',
  danger: '#FB7185',
  warning: '#FBBF24',
  border: '#334155',
  cardShadow: 'rgba(0, 0, 0, 0.3)',
  overlay: 'rgba(0,0,0,0.7)',
  skeleton: '#334155',
  skeletonHighlight: '#475569',
  tabBar: '#1E293B',
  inputBg: '#334155',
  headerBg: '#1E293B',
  statBg: '#1E293B',
  dangerLight: '#451A1A',
  warningLight: '#451A03',
};

export const globalStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 20,
    marginVertical: 10,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.border,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textLight,
  },
  button: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 12,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  buttonSecondary: {
    backgroundColor: colors.primaryLight,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 8,
  },
  buttonSecondaryText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  input: {
    backgroundColor: colors.inputBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: colors.text,
    marginVertical: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
    marginTop: 8,
    marginBottom: 4,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    marginTop: 4,
  },
  largeNumber: {
    fontSize: 36,
    fontWeight: 'bold',
    color: colors.primary,
  },
  textLight: {
    fontSize: 14,
    color: colors.textLight,
  },
});
